version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - zip -r function.zip src/handler.ts src/routes/ src/models/ src/middleware/ src/services/ node_modules/
      - aws s3 cp function.zip s3://blackjack-node-bucket/function.zip
artifacts:
  files:
    - function.zip
